name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install and Build
        run: |
          cd client/wastmanagemet
          npm install
          npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/wastmanagemet/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub
        id: deployment
        uses: actions/deploy-pages@v4
